locale                   : "en-US"
site_theme               : "default"
title                    : "Junteng Liu"
title_separator          : "-"
name                     : &name "Junteng Liu"
description              : &description "Junteng Liu's academic portfolio"
url                      : https://hkustnlp-cmyk.github.io/LJT-Homepage
baseurl                  : ""
repository               : "hkustnlp-cmyk/LJT-Homepage"

author:
  avatar           : ""
  name             : "Junteng Liu"
  bio              : "First-year PhD candidate at HKUST NLP Group"
  location         : "Hong Kong"
  employer         : "Hong Kong University of Science and Technology"
  email            : "jliugi@connect.ust.hk"

  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github           : "Vicent0205"
  twitter          : "junteng88716710"

publication_category:
  conferences:
    title: 'Publications'

collections:
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
